FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y postgresql-client
#node.10.xにしないとcssのフレームワークを入れるとエラーがでる。
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
 && apt-get install -y nodejs
RUN mkdir /myapp
WORKDIR /myapp

COPY Gemfile /myapp
COPY Gemfile.lock /myapp
RUN gem install bundler & bundle install

COPY . /myapp
